services:
  portfolio:
    image: ghcr.io/rgardel/portfolio-publico:latest
    container_name: portfolio-publico
    restart: unless-stopped
    ports:
      - "3000:80"        # Nginx Proxy Manager apuntará a este puerto
    environment:
      - TZ=Europe/Madrid
